### ISSUE TITLE
Pick a license

### ISSUE THREAD

**Issue by justwheel** [RITlug/config-management#1]
Before getting deep into this, we should decide on a license to use for the project. It depends if we want a copyleft-type license or a permissive-type license. To get us started, I will suggest two options. I have two suggestions of my preferred licenses for each type:

# Option 1: Mozilla Public License 2.0 [![License: MPL 2.0](https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg)](https://opensource.org/licenses/MPL-2.0)

This is my preferred license for open source infrastructure projects.

The MPL permits others to use our work for any purpose, distribute the work, and combine it independently from proprietary work. However, if any _changes_ are made to our work, those changes must also be made open source. I prefer this license because it gives flexibility for others to reuse this work for any purpose (even combining it with proprietary work, unlike the GPL), but if changes are made to our source material, those changes must be open sourced.

[_See tldrlegal.com for more._](https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2))

# Option 2: BSD 3-Clause License [![License: BSD 3-Clause License](https://img.shields.io/badge/License-BSD%203--Clause-blue.svg)](https://opensource.org/licenses/BSD-3-Clause)

This is my preferred permissive license, but not necessarily for open infrastructure projects. It offers somewhat more direction than the MIT License, but not much. Good for when want as few restrictions on reuse and modifications as possible without compromising on citing original authors correctly and having limited liability.

[_See tldrlegal.com for more._](https://tldrlegal.com/license/bsd-3-clause-license-(revised))

**Comment by jrtechs** [comment]
Personally, I prefer the Mozilla Public License since it requires clones/forks to be opensource. However, I would have no issue with the BSD license

**Comment by justwheel** [comment]
@Tjzabel @jrtechs Feel free to leave an approval on #2 for the license PR too.
