### ISSUE TITLE
Facilitate ITS introduction and IP assignment increase/waiver

### ISSUE THREAD

**Issue by icflournoy** [RITlug/config-management#11]
Solomon has a contact at ITS that manages the club's IP allocation.

**Actions**
- Have eboard members (@Tjzabel ... ?) introduced to contact at ITS
- Learn what the process is for increasing or waivering the IP limit for the club, so that we can assign addresses to the CBET cluster

**Comment by ct-martin** [comment]
Introductions were made. Next steps are completing exchange of emails (cc @Serubin - not sure if you send our info to them, but I don't have their info either) and doing the paperwork to increase our IP limit. For CBET, we were told to email them the MAC address of the server that will go down there and they will add it for us.

**Comment by ct-martin** [comment]
For clarity, only @jrtechs & I were given introductions; @Tjzabel was not on-campus so he wasn't there.

**Comment by Tjzabel** [comment]
I have no idea the status of this issue.

**Comment by Tjzabel** [comment]
Still don't know what ever happened with this issue. Closing this issue for now, it can be reopened in the future if need be.
