### ISSUE TITLE
Set RITlug GitLab to autorenew Let's Encrypt cert

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/config-management#12]
Currently the hosted gitlab does not autorenew, and so we run into issues where the gitlab goes down.

We should add this as a cron job so we do not need to do this manually.

**Comment by ct-martin** [comment]
@Tjzabel thanks, confirmed that I can access and changed password. When you fixed it, did you do a one-off renew or did you set up the auto-renew?

**Comment by Tjzabel** [comment]
@ct-martin for written reference, I did a one-off renew.

**Comment by Tjzabel** [comment]
From looking in cron, it seems git.ritlug.com is indeed renewing. Closing as fixed.
