### ISSUE TITLE
Deprecate unused email aliases

### ISSUE THREAD

**Issue by ct-martin** [RITlug/config-management#13]
This is an action item coming from RITlug/tasks#93 & RITlug/tasks#95 to remove unused email aliases.

List of emails to verify they aren't used/mentioned anywhere current and remove:
* `president@`
* `secretary@`
* `treasurer@`
* `vicepresident@`

Others that exist that we may or may not want to consider keeping:
* `advisor@` (goes to SJ)
* `info@` (alias of `eboard@`)

**Comment by Tjzabel** [comment]
I deleted the `info` record, as I don't see a logical time when we would want to give this alias out.

All other aliases I would like to keep, so closing issue as complete.
