### ISSUE TITLE
Rename to RITlug/Infrastructure?

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/config-management#3]
While config-management *is* what this repository would hold, I am wondering if it would make sense to rename this repository to keep in line with FOSSRIT/Infrastructure, and also give others a better understanding that this repository hosts config-management *for our infrastructure*.

@RITlug/eboard-current Thoughts?

**Comment by ct-martin** [comment]
@Tjzabel fine by me. We also might want to consider moving the TigerOS playbooks here too.
