### ISSUE TITLE
Remove prefix on Slack bridge

### ISSUE THREAD

**Issue by ct-martin** [RITlug/config-management#5]
The name of the Slack bridge bot (`slack-ritlug`) tells us where it's coming from, so the extra `[slack] ` prefix is redundant

**Comment by justwheel** [comment]
@ct-martin Could you reopen this in FOSSRIT/infrastructure since the bot is managed there? I'm planning to swing through a few things after the New Year for MAGIC.

I tried to transfer this issue with the beta feature, but it doesn't work for cross-organization repos.
