### ISSUE TITLE
Host a Nextcloud instance for club members

### ISSUE THREAD

**Issue by justwheel** [RITlug/config-management#6]
From a short discussion in IRC with @Serubin about hosting a [Nextcloud](https://nextcloud.com) instance for club members. More details to come soon.

**Comment by ct-martin** [comment]
Install done, adding policy to agenda for discussion

**Comment by Tjzabel** [comment]
I'm blocking this issue on #31 for @ct-martin to configure NextCloud for the eboard members to test out.

**Comment by Tjzabel** [comment]
Hmmm... I'm wondering at this point if we will have bandwidth this semester/year to go through with hosting NextCloud for our club members.

**Comment by nlMeminger** [comment]
I think this might be too difficult to maintain for everyone in the club. I
wouldn’t be opposed to closing this since I know I likely won’t have the
bandwidth either.

**Comment by Tjzabel** [comment]
Closing as out of scope.
