### ISSUE TITLE
Update IP Allocation Page in RITlug GitLab

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/config-management#9]
The IP allocation project within the RITlug GitLab is currently out of date. It would be good to update this page so we know what resources we can make use of.

**Comment by ct-martin** [comment]
I can get raw allocations from CLAWS, but I have no access to what they're
being used for (yet)

--
Christian Martin (Phone)

**Comment by ct-martin** [comment]
Only change change needed was ListenBrainz being deprecated. I also added a note about the container for holding MAC addresses
